### ISSUE TITLE
Heroku: ImportError: No module named local

### ISSUE THREAD

**Issue by awhillas** [xenith/django-base-template#31]
I don't know if anyone has got this going on Heroku but i can't get passed this error message:

```
2015-12-01T11:00:29.615984+00:00 app[web.1]:     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
2015-12-01T11:00:29.615985+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
2015-12-01T11:00:29.615987+00:00 app[web.1]:     self._wrapped = Settings(settings_module)
2015-12-01T11:00:29.615985+00:00 app[web.1]:     self._setup(name)
2015-12-01T11:00:29.615986+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
2015-12-01T11:00:29.615988+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
2015-12-01T11:00:29.615989+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/importlib/__init__.py", line 37, in import_module
2015-12-01T11:00:29.615990+00:00 app[web.1]:     __import__(name)
2015-12-01T11:00:29.615990+00:00 app[web.1]:   File "/app/basic/settings/__init__.py", line 6, in <module>
2015-12-01T11:00:29.616059+00:00 app[web.1]: Traceback (most recent call last):
2015-12-01T11:00:29.615988+00:00 app[web.1]:     mod = importlib.import_module(self.SETTINGS_MODULE)
2015-12-01T11:00:29.615991+00:00 app[web.1]:     from .local import *
2015-12-01T11:00:29.616060+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
2015-12-01T11:00:29.616066+00:00 app[web.1]:     self.callable = self.load()
2015-12-01T11:00:29.615996+00:00 app[web.1]: ImportError: No module named local
2015-12-01T11:00:29.616079+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
2015-12-01T11:00:29.616057+00:00 app[web.1]: [2015-12-01 11:00:29 +0000] [10] [ERROR] Exception in worker process:
2015-12-01T11:00:29.616062+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
2015-12-01T11:00:29.616068+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2015-12-01T11:00:29.616080+00:00 app[web.1]:     django.setup()
2015-12-01T11:00:29.616080+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/__init__.py", line 17, in setup
2015-12-01T11:00:29.616082+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
2015-12-01T11:00:29.616070+00:00 app[web.1]:     __import__(module)
2015-12-01T11:00:29.616061+00:00 app[web.1]:     worker.init_process()
2015-12-01T11:00:29.616064+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2015-12-01T11:00:29.616065+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2015-12-01T11:00:29.616069+00:00 app[web.1]:     return util.import_app(self.app_uri)
2015-12-01T11:00:29.616088+00:00 app[web.1]:     from .local import *
2015-12-01T11:00:29.616089+00:00 app[web.1]: Traceback (most recent call last):
2015-12-01T11:00:29.616063+00:00 app[web.1]:     self.load_wsgi()
2015-12-01T11:00:29.616063+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
2015-12-01T11:00:29.616067+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2015-12-01T11:00:29.616078+00:00 app[web.1]:     application = get_wsgi_application()
2015-12-01T11:00:29.616067+00:00 app[web.1]:     return self.load_wsgiapp()
2015-12-01T11:00:29.616089+00:00 app[web.1]: ImportError: No module named local
2015-12-01T11:00:29.616091+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
2015-12-01T11:00:29.616070+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 354, in import_app
2015-12-01T11:00:29.616081+00:00 app[web.1]:     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
2015-12-01T11:00:29.616083+00:00 app[web.1]:     self._wrapped = Settings(settings_module)
2015-12-01T11:00:29.616085+00:00 app[web.1]:     mod = importlib.import_module(self.SETTINGS_MODULE)
2015-12-01T11:00:29.616086+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/importlib/__init__.py", line 37, in import_module
2015-12-01T11:00:29.616087+00:00 app[web.1]:     __import__(name)
2015-12-01T11:00:29.616077+00:00 app[web.1]:   File "/app/basic/heroku_wsgi.py", line 16, in <module>
2015-12-01T11:00:29.616082+00:00 app[web.1]:     self._setup(name)
2015-12-01T11:00:29.616090+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
2015-12-01T11:00:29.616090+00:00 app[web.1]:     worker.init_process()
2015-12-01T11:00:29.616093+00:00 app[web.1]:     self.load_wsgi()
2015-12-01T11:00:29.616096+00:00 app[web.1]:     self.callable = self.load()
2015-12-01T11:00:29.616083+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
2015-12-01T11:00:29.616087+00:00 app[web.1]:   File "/app/basic/settings/__init__.py", line 6, in <module>
2015-12-01T11:00:29.616098+00:00 app[web.1]:     return util.import_app(self.app_uri)
2015-12-01T11:00:29.616104+00:00 app[web.1]:     __import__(module)
2015-12-01T11:00:29.616084+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
2015-12-01T11:00:29.616095+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2015-12-01T11:00:29.616097+00:00 app[web.1]:     return self.load_wsgiapp()
2015-12-01T11:00:29.616094+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
2015-12-01T11:00:29.616094+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2015-12-01T11:00:29.616096+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2015-12-01T11:00:29.616108+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
2015-12-01T11:00:29.616111+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
2015-12-01T11:00:29.616113+00:00 app[web.1]:   File "/app/basic/settings/__init__.py", line 6, in <module>
2015-12-01T11:00:29.616111+00:00 app[web.1]:     mod = importlib.import_module(self.SETTINGS_MODULE)
2015-12-01T11:00:29.616112+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/importlib/__init__.py", line 37, in import_module
2015-12-01T11:00:29.616118+00:00 app[web.1]: ImportError: No module named local
2015-12-01T11:00:29.616114+00:00 app[web.1]:     from .local import *
2015-12-01T11:00:29.639425+00:00 app[web.1]: Traceback (most recent call last):
2015-12-01T11:00:29.639429+00:00 app[web.1]:   File "/app/.heroku/python/bin/gunicorn", line 11, in <module>
2015-12-01T11:00:29.616103+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 354, in import_app
2015-12-01T11:00:29.616098+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2015-12-01T11:00:29.616104+00:00 app[web.1]:   File "/app/basic/heroku_wsgi.py", line 16, in <module>
2015-12-01T11:00:29.616105+00:00 app[web.1]:     application = get_wsgi_application()
2015-12-01T11:00:29.616107+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/__init__.py", line 17, in setup
2015-12-01T11:00:29.616109+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
2015-12-01T11:00:29.616105+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
2015-12-01T11:00:29.616106+00:00 app[web.1]:     django.setup()
2015-12-01T11:00:29.616108+00:00 app[web.1]:     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
2015-12-01T11:00:29.616109+00:00 app[web.1]:     self._setup(name)
2015-12-01T11:00:29.616110+00:00 app[web.1]:     self._wrapped = Settings(settings_module)
2015-12-01T11:00:29.616113+00:00 app[web.1]:     __import__(name)
2015-12-01T11:00:29.639434+00:00 app[web.1]:     sys.exit(run())
2015-12-01T11:00:29.639597+00:00 app[web.1]:     Arbiter(self).run()
2015-12-01T11:00:29.639703+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 302, in halt
2015-12-01T11:00:29.639898+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 464, in reap_workers
2015-12-01T11:00:29.639491+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 192, in run
2015-12-01T11:00:29.639771+00:00 app[web.1]:     self.stop()
2015-12-01T11:00:29.639774+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 347, in stop
2015-12-01T11:00:29.640028+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2015-12-01T11:00:29.639545+00:00 app[web.1]:     super(Application, self).run()
2015-12-01T11:00:29.639626+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 206, in run
2015-12-01T11:00:29.639895+00:00 app[web.1]:     self.reap_workers()
2015-12-01T11:00:29.639842+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 219, in handle_chld
2015-12-01T11:00:29.616119+00:00 app[web.1]: [2015-12-01 11:00:29 +0000] [9] [INFO] Worker exiting (pid: 9)
2015-12-01T11:00:29.616215+00:00 app[web.1]: [2015-12-01 11:00:29 +0000] [10] [INFO] Worker exiting (pid: 10)
2015-12-01T11:00:29.639435+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
2015-12-01T11:00:29.639699+00:00 app[web.1]:     self.halt(reason=inst.reason, exit_status=inst.exit_status)
2015-12-01T11:00:29.639469+00:00 app[web.1]:     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
2015-12-01T11:00:29.639548+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
2015-12-01T11:00:29.639839+00:00 app[web.1]:     time.sleep(0.1)
2015-12-01T11:00:29.639977+00:00 app[web.1]:     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
2015-12-01T11:00:30.334116+00:00 heroku[web.1]: State changed from starting to crashed
2015-12-01T11:00:30.332471+00:00 heroku[web.1]: Process exited with status 1
```

**Comment by awhillas** [comment]
yes, i renamed the local-dist.py to local.py. It imports .base in the same dir. but seems to ignore local.py???

**Comment by xenith** [comment]
Did you make sure local.py is committed to git? I include a .gitignore file that ignores settings/local.py, so you need to force add it.

**Comment by awhillas** [comment]
Was a Heroku problem. Seems to have a specific issue with the name local.py. Works if you change the name
